#!/usr/bin/env bash

# ==========================================
# GHOST
# Disk Space Investigator
# Version 0.5
# ==========================================

set -u

# ==========================================
# CONFIGURATION
# ==========================================

CACHE_DIR="$HOME/.cache"
NPM_DIR="$HOME/.npm"
DOWNLOADS_DIR="$HOME/Downloads"
VAR_DIR="$HOME/.var"
LOCAL_DIR="$HOME/.local"
DOCKER_DIR="$HOME/.docker"

# ==========================================
# HEADER
# ==========================================

show_header() {
    echo
    echo "=========================================="
    echo "       GHOST - Disk Space Investigator"
    echo "=========================================="
    echo
}

# ==========================================
# FORMAT BYTES
# ==========================================

format_bytes() {
    local bytes="$1"

    if (( bytes >= 1073741824 )); then
        awk "BEGIN {printf \"%.2f GB\", $bytes / 1073741824}"
    elif (( bytes >= 1048576 )); then
        awk "BEGIN {printf \"%.2f MB\", $bytes / 1048576}"
    elif (( bytes >= 1024 )); then
        awk "BEGIN {printf \"%.2f KB\", $bytes / 1024}"
    else
        echo "${bytes} B"
    fi
}

# ==========================================
# GET DIRECTORY SIZE
# ==========================================

get_directory_size() {
    local directory="$1"

    if [[ ! -d "$directory" ]]; then
        echo "0"
        return
    fi

    du -sB1 "$directory" 2>/dev/null | awk '{print $1}'
}

# ==========================================
# DISK USAGE
# ==========================================

show_disk_usage() {
    echo "SYSTEM STORAGE"
    echo "------------------------------------------"
    echo

    df -h "$HOME" | awk 'NR==2 {
        printf "Total:       %s\n", $2
        printf "Used:        %s\n", $3
        printf "Available:   %s\n", $4
        printf "Usage:       %s\n", $5
    }'

    echo
}

# ==========================================
# TOP DIRECTORIES
# ==========================================

show_top_directories() {
    echo "TOP DIRECTORIES"
    echo "------------------------------------------"
    echo

    du -h --max-depth=1 "$HOME" 2>/dev/null |
        sort -hr |
        head -n 10

    echo
}

# ==========================================
# LARGE FILE INVESTIGATOR
# ==========================================

find_large_files() {
    show_header

    echo "LARGE FILE INVESTIGATOR"
    echo "------------------------------------------"
    echo
    echo "Scanning: $HOME"
    echo "Looking for files larger than 500 MB..."
    echo

    files=$(
        find "$HOME" \
            -type f \
            -size +500M \
            -printf '%p\n' \
            2>/dev/null
    )

    if [[ -z "$files" ]]; then
        echo "No files larger than 500 MB were found."
        echo
        return
    fi

    printf "%-15s %-15s %s\n" "ACTUAL" "LOGICAL" "FILE"
    printf "%-15s %-15s %s\n" "------" "-------" "----"

    while IFS= read -r file; do

        logical=$(stat -c '%s' "$file" 2>/dev/null)
        actual=$(du -B1 "$file" 2>/dev/null | awk '{print $1}')

        if [[ -z "$logical" || -z "$actual" ]]; then
            continue
        fi

        logical_display=$(format_bytes "$logical")
        actual_display=$(format_bytes "$actual")

        printf "%-15s %-15s %s\n" \
            "$actual_display" \
            "$logical_display" \
            "$file"

    done <<< "$files"

    echo
}

# ==========================================
# GHOST DETECTION
# ==========================================

detect_ghost() {
    local name="$1"
    local path="$2"
    local type="$3"
    local risk="$4"
    local recommendation="$5"

    if [[ ! -d "$path" ]]; then
        return
    fi

    local size
    size=$(get_directory_size "$path")

    if [[ "$size" == "0" ]]; then
        return
    fi

    echo "👻 $name"
    echo "   Location:       $path"
    echo "   Size:           $(format_bytes "$size")"
    echo "   Type:           $type"
    echo "   Risk:           $risk"
    echo "   Recommendation: $recommendation"
    echo
}

detect_ghosts() {
    show_header

    echo "GHOST DETECTION"
    echo "------------------------------------------"
    echo
    echo "Searching for known storage consumers..."
    echo

    detect_ghost \
        "Docker Storage" \
        "$DOCKER_DIR" \
        "Development environment" \
        "REVIEW" \
        "Inspect unused Docker images, containers and volumes."

    detect_ghost \
        "Downloads" \
        "$DOWNLOADS_DIR" \
        "User files" \
        "REVIEW" \
        "Check old installers, archives and unused downloads."

    detect_ghost \
        "Application Cache" \
        "$CACHE_DIR" \
        "Application cache" \
        "LOW" \
        "Cache data can usually be regenerated by applications."

    detect_ghost \
        "NPM Cache" \
        "$NPM_DIR" \
        "Package manager cache" \
        "LOW" \
        "Unused npm cache can usually be regenerated."

    detect_ghost \
        "User Data" \
        "$LOCAL_DIR" \
        "Application data" \
        "REVIEW" \
        "Inspect before removing anything."

    detect_ghost \
        "Application Storage" \
        "$VAR_DIR" \
        "Application storage" \
        "REVIEW" \
        "Inspect installed applications and their data."

    echo "------------------------------------------"
    echo
    echo "Ghost detection complete."
    echo
}

# ==========================================
# DIRECTORY INSPECTOR
# ==========================================

inspect_directory() {
    local directory="$1"

    # Expand "~" manually if supplied.
    if [[ "$directory" == "~" ]]; then
        directory="$HOME"
    elif [[ "$directory" == "~/"* ]]; then
        directory="$HOME/${directory#~/}"
    fi

    # Convert relative paths to absolute paths.
    if [[ "$directory" != /* ]]; then
        directory="$(realpath "$directory" 2>/dev/null || echo "$directory")"
    fi

    if [[ ! -d "$directory" ]]; then
        echo
        echo "Error: directory does not exist."
        echo "Path: $directory"
        echo
        exit 1
    fi

    show_header

    echo "DIRECTORY INSPECTOR"
    echo "------------------------------------------"
    echo
    echo "Path:"
    echo "  $directory"
    echo

    local total_size
    total_size=$(get_directory_size "$directory")

    echo "Total size:"
    echo "  $(format_bytes "$total_size")"
    echo

    echo "CONTENTS"
    echo "------------------------------------------"
    echo

    printf "%-15s %s\n" "SIZE" "PATH"
    printf "%-15s %s\n" "----" "----"

    du -sB1 "$directory"/* "$directory"/.[!.]* "$directory"/..?* 2>/dev/null |
        sort -nr |
        head -n 15 |
        while read -r size path; do
            printf "%-15s %s\n" "$(format_bytes "$size")" "$path"
        done

    echo
}

# ==========================================
# FULL SYSTEM SCAN
# ==========================================

scan() {
    show_header
    show_disk_usage
    show_top_directories
}

# ==========================================
# HELP
# ==========================================

show_help() {
    show_header

    echo "Usage:"
    echo "  ./ghost.sh <command>"
    echo

    echo "Commands:"
    echo "  scan              Scan disk usage"
    echo "  large             Find files larger than 500 MB"
    echo "  ghosts            Detect storage ghosts"
    echo "  inspect <path>    Inspect a directory"
    echo "  help              Show this help message"
    echo
}

# ==========================================
# COMMAND ROUTER
# ==========================================

case "${1:-help}" in

    scan)
        scan
        ;;

    large)
        find_large_files
        ;;

    ghosts)
        detect_ghosts
        ;;

    inspect)
        if [[ -z "${2:-}" ]]; then
            echo
            echo "Error: inspect requires a directory."
            echo
            echo "Example:"
            echo "  ./ghost.sh inspect ~/.cache"
            echo
            exit 1
        fi

        inspect_directory "$2"
        ;;

    help)
        show_help
        ;;

    *)
        echo
        echo "Unknown command: $1"
        echo "Run './ghost.sh help' for usage."
        echo
        exit 1
        ;;

esac